name: Minebattle
main: src.main.java.net.link404.minebattle.App
version: 0.0.1

commands:
  web:
    description: Displays our web links.
  anon:
    description: send stuff to ppl.
    usage: "/anon <player> <message>"